version: '3'
services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend:/workspace
    env_file:
      - ../backend/.env
    ports:
      - "8080:8080"
    command: sleep infinity

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/workspace
    ports:
      - "5173:5173"
    command: sleep infinity
    depends_on:
      - backend